### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by xBrandonGx97** [gugglegum/phpstorm-reset-trial#4]
https://i.imgur.com/dkrk6VG.png

**Comment by gugglegum** [comment]
@xBrandonGx97 which version of PHP do you use? This script requires PHP 7.0 or higher. You're probably using PHP 5.x ?

**Comment by xBrandonGx97** [comment]
yeah, 5.6

**Comment by xBrandonGx97** [comment]
there's no version that's compatible with 5.6?

**Comment by gugglegum** [comment]
@xBrandonGx97, sorry. Unfortunately no. PHP 7.0 is a minimum version. PHP7 was released more than 3 years ago, many projects and libraries now require 7.0 as a minimum version. So I decided there's no need to support obsoleted 5.x version.

But even if you can't upgrade to PHP7 by any reason, you can install standalone PHP7. Without configuring it in web-server. Just unzip PHP 7 in any temporary folder and run phpstorm_reset_trial from there.
